### ISSUE TITLE
Panic on default blake2b params with 32 byte output

### ISSUE THREAD

**Issue by gtank** [gtank/blake2#1]
Reported on Twitter: https://twitter.com/Elichai2/status/1336999936936849411 by @elichai

> It panics on this code:
> ```
> blake, _ := blake2b.NewDigest(nil, nil, nil, 32)
> blake.Write(buf[:])
> blake.Sum(nil)
>```

This feels like it's probably going to be an uninitialized slice somewhere. But it's surprising that tests or usage haven't caught it; I guess they all define some parameter or other, that being the motivation for the library. Whoops.

**Comment by elichai** [comment]
I'm on my phone now so can't check, but I don't think that's the problem.
I'm pretty sure the problem is with any non 64-byte output,because the Sum function unconditionally tries to write out the full 512bit output

**Comment by gtank** [comment]
Good catch, that's totally what was going on! The actual oversight was that Zcash usage and the official vectors all use full-length outputs, so I never tested this despite implementing the option.

I have the issue fixed in a branch now and will cut a new release with the fix (...and tests) soon.

edit: [v0.1.1](https://github.com/gtank/blake2/releases/tag/v0.1.1) is out.
